name: Performance Profiling Tests

on:
  push:
    branches: [main]
  pull_request:
    types: [labeled]
  issue_comment:
    types: [created]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  performance-profiling:
    runs-on: ubuntu-latest
    # Only run if:
    # - Push to main branch
    # - PR labeled with 'performance-test'
    # - Comment contains '/performance-test'
    # - Manual trigger
    if: |
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && contains(github.event.label.name, 'performance-test')) ||
      (github.event_name == 'issue_comment' && 
       github.event.issue.pull_request && 
       contains(github.event.comment.body, '/performance-test'))

    env:
      DISPLAY: :99

    steps:
      - name: Get PR info
        if: github.event_name == 'issue_comment'
        id: pr
        run: |
          echo "number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
          echo "head_sha=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.issue.number }}" | \
            jq -r .head.sha)" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'issue_comment' && steps.pr.outputs.head_sha || github.sha }}
      - uses: subosito/flutter-action@v2
      - name: Install Linux dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev
          sudo apt-get install -y xvfb
          sudo apt-get install -y libegl1-mesa-dev libgl1-mesa-dev libgles2-mesa-dev
          sudo apt-get install -y mesa-common-dev

      - name: Get Flutter dependencies
        working-directory: ./examples/testing
        run: flutter pub get

      - name: Start virtual display
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          sleep 3

      - name: Run performance profiling tests
        working-directory: ./examples/testing
        env:
          DISPLAY: :99
        run: |
          flutter drive \
            --driver=test_driver/perf_driver.dart \
            --target=integration_test/performance_profiling_test.dart \
            --profile \
            -d linux

      - name: List generated files
        working-directory: ./examples/testing
        run: |
          echo "Generated performance files:"
          find . -name "*.timeline_summary.json" -o -name "*.timeline.json" | head -20

      - name: Upload performance reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: performance-reports-${{ github.run_number }}
          path: |
            examples/testing/build/*.timeline.json
            examples/testing/performance_summary.json
          retention-days: 30
